INSERT INTO
    trainer (
        discord,
        battlefy,
        twitter,
        realname,
        nickname,
        country,
        created_by,
        updated_by
    )
VALUES
('Albertiti#4754','albertiti','Albertiti48','Alberto',,'Alberto','ES','pikuchanneru','pikuchanneru'),
('Aldrich#7563','rich_yan','AldrichYan','Aldrich Yan Sutandra',,'AldrichYan','ID','pikuchanneru','pikuchanneru'),
('Mkh#3748','alvinsoyol','AnabelVg','Mak Kwan Ho',,'AnabelVg','HK','pikuchanneru','pikuchanneru'),
('ᴀɴᴅʏ#1000','aapbrophy','andy_pkmn',NULL,,'Andy','AU','pikuchanneru','pikuchanneru'),
('kakubi#1166','bi69forgame',NULL,'Quang Ong',,'Bi','VN','pikuchanneru','pikuchanneru'),
('DaMuGa#0577','damuga89','DaniMunueraGar','Daniel Munuera García',,'DaMuGa','ES','pikuchanneru','pikuchanneru'),
('Dereking#1677','derekbolher','azaelbolanos','Derek Azael Bolaños Hernández',,'DerekAZ🇲🇽','MX','pikuchanneru','pikuchanneru'),
('Aric#2352','huicong04',NULL,'Huicong Chen',,'dlwlrm','CN','pikuchanneru','pikuchanneru'),
('Enje#0505','enjevgc','EnjeVGC','Nicholas Johnson',,'Enje','ID','pikuchanneru','pikuchanneru'),
('funyy253#1142','phantruongthinh2013','TrngThnhPhan1','Thinh Phan',,'funny253','VN','pikuchanneru','pikuchanneru'),
('Anselm#2590','anselmespunysanchis','OakVgc','Anselm Espuny Sanchis',,'Gary Oak','ES','pikuchanneru','pikuchanneru'),
('bufer#9280','2506596454',NULL,'Zijian He',,'GTM指挥部','CN','pikuchanneru','pikuchanneru'),
('友亮#7431','brandon1221t','Brandontingvgc','Yu-Liang Ting',,'Haru','TW','pikuchanneru','pikuchanneru'),
('IBOIII#1111','dalisebastian06','notIBOIII','Dali S. P. Noviyanto',,'IBOIII','ID','pikuchanneru','pikuchanneru'),
('ohmyjosh#9491','joshuajohnf','ohohohmyJOSH',NULL,,'Jet','PH','pikuchanneru','pikuchanneru'),
('Karaikou#4714','karaikou','KaraikouVGC',NULL,,'Karaikou','AU','pikuchanneru','pikuchanneru'),
('kimnaise#4156','hakim_possible5','kimnaise','Hakim Nah',,'Kimnaise','SG','pikuchanneru','pikuchanneru'),
('Card Captor Sakura Dragona','lemepa11','Lemepa11','Leslie Mendoza',,'Leslie Mendoza','PR','pikuchanneru','pikuchanneru'),
('luongthanh#4872','luongthanh',NULL,'Luong Thanh',,'Lucifer','VN','pikuchanneru','pikuchanneru'),
('Mayburn#5936','josua111',NULL,'Josua S. Marbun',,'Mayburn','ID','pikuchanneru','pikuchanneru'),
('Mufasa#5416','jmainey99493','mufasa_245','James Mainey',,'Mufasa','AU','pikuchanneru','pikuchanneru'),
('multi_boy#2105','multiboyvgc','MultiBoyvgc','Lewis Tan',,'Multi boy','AU','pikuchanneru','pikuchanneru'),
('Nak#7379','darkrai194','XDLuciferZ','Thinh Lê',,'Nak','VN','pikuchanneru','pikuchanneru'),
('Patrick#4842','patrick123123123','Patrick_VGC','Patrick Cheng',,'Patricia','HK','pikuchanneru','pikuchanneru'),
('HungChu#6985','chumanhhung0307',NULL,NULL,,'Peralta','VN','pikuchanneru','pikuchanneru'),
('Percy Ng#3864','percyvgc',NULL,'Percy Ng',,'Percy','HK','pikuchanneru','pikuchanneru'),
('pocoyo#3835','76pocoyo','76pocoyo','Kenny Ongkojoyo',,'pocoyo','ID','pikuchanneru','pikuchanneru'),
('PokeSol#6969','pokesolft','PokeSoll?s=09','Hugo Gómez',,'PokeSol','ES','pikuchanneru','pikuchanneru'),
('PPA','pppppa',NULL,'Puan Pan',,'PPPPPA','CN','pikuchanneru','pikuchanneru'),
('SkyFlyHigh#9743','blastingkhoo',NULL,'Harrold Khoo',,'SkyFlyHigh ','SG','pikuchanneru','pikuchanneru'),
('とり。＃4623','fakekotori','cantfly_ss',NULL,,'tori.','JP','pikuchanneru','pikuchanneru'),
('Waffles#9099','wafflestheasianyenbear','TheAsianYenbear','Alex Usami',,'Waffles','JP','pikuchanneru','pikuchanneru'),
('Xeb41#7034','baziotisioannis','Xeb_41','Baziotis Ioannis',,'Xeb41','GR','pikuchanneru','pikuchanneru'),
('TextFont#3519','pretzy91','Textfont','Wai Yin Low',,'Yin','SG','pikuchanneru','pikuchanneru'),
('アカザ#0152','irekise9416','akaza0727',NULL,,'アカザ','JP','pikuchanneru','pikuchanneru'),
('Kassiddy#0974','kischnp','Kassiddy_VGC',NULL,,'Kassiddy','HK','pikuchanneru','pikuchanneru'),
('Jekyll334#6225','jekyll334','jekyll335','Satoru Mutsuno',,'ジキル','JP','pikuchanneru','pikuchanneru'),
('ike#8123','いけちゃん','ike_poke',NULL,,'ソード','JP','pikuchanneru','pikuchanneru'),
('tyo#0303','itsumoreddy','raisedintyo','Nikhil Reddy',,'ニキル','JP','pikuchanneru','pikuchanneru'),
('ぽんぽんた#2372','ぽんぽんた','ponponta1019',NULL,,'ぽんぽんた','JP','pikuchanneru','pikuchanneru'),
('历音#5806','1059606295',NULL,NULL,,'历音','CN','pikuchanneru','pikuchanneru'),
('TheCui#3978','thecui',NULL,'Yiwen Bao',,'若白不是攻','CN','pikuchanneru','pikuchanneru'),
('葱烧板栗#4499','葱烧板栗',NULL,'Zheyu Lin',,'葱烧板栗','CN','pikuchanneru','pikuchanneru'),
('Jingshu LiVGC','603770997',NULL,'Jingshu Li',,'鲁路修四海','CN','pikuchanneru','pikuchanneru')
    
     ON CONFLICT (id) DO
UPDATE
SET
    discord = EXCLUDED.discord,
    battlefy = EXCLUDED.battlefy,
    twitter = EXCLUDED.twitter,
    realname = EXCLUDED.realname,
    nickname = EXCLUDED.nickname,
    country = EXCLUDED.country,
    created_by = EXCLUDED.created_by,
    updated_by = EXCLUDED.updated_by;