INSERT INTO
    trainer (
        discord,
        battlefy,
        twitter,
        realname,
        nickname,
        country,
        created_by,
        updated_by
    )
VALUES
    (
        "AussiePhilNguyen#1806",
        "aussiephilnguyen",
        "Aussie_Phil_N",
        NULL,
        "Phil Nguyen",
        "AU"
    ),
    (
        "Baars#2096",
        "basvdhaarnhoorn",
        "BaarsKaasVGC",
        NULL,
        "Priscilla",
        "CX"
    ),
    (
        "Bahamuth#6605",
        "danieljonathan97",
        "MDanielJonathan",
        NULL,
        "Bahamuth",
        "ID"
    ),
    (
        "bankaisr#3986",
        "15bankai1998",
        NULL,
        NULL,
        "Nhiên Hina",
        "VN"
    ),
    (
        "blank#1264",
        "giolozanooumwa",
        NULL,
        NULL,
        "Gio (Patrick Santos)",
        "PH"
    ),
    (
        "DarkJorch#5424 ",
        "jorgeyayo2004",
        NULL,
        NULL,
        "DarkJorch ",
        "ES"
    ),
    (
        "dddDayDaybbb#1662",
        "718534061",
        "DayDay84400880",
        NULL,
        "DayDaysfw",
        "CN"
    ),
    ("Eutectic#4945", "eutectic", NULL, NULL, "Zent", "ID"),
    (
        "fvgb40#3046",
        "fvgb40",
        "fvgb40",
        NULL,
        "fvgb40",
        "AU"
    ),
    ("Gin #7889", "ginjr", "gipaarrr", NULL, "Gin", "ID"),
    (
        "Gon#6122",
        "churrerovgc",
        "ElChurrero13",
        NULL,
        "Gon",
        "ES"
    ),
    (
        "imrobberting#7130",
        "rb1cuartero",
        "imrobberting",
        NULL,
        "Rob",
        "PH"
    ),
    (
        "Jayden1200#6349",
        "jayden120",
        "jayden120000",
        NULL,
        "jayden120",
        "AU"
    ),
    (
        "JenZzz#9907",
        "jenssoto",
        "soto_jens",
        NULL,
        "Jenzzz",
        "PR"
    ),
    (
        "Kaizen#5257",
        "avsyap",
        "KaizenVGC",
        NULL,
        "Andrew",
        "PH"
    ),
    (
        "kakunaka#9011",
        "shinichi123mm",
        "kakunaka_VGC",
        NULL,
        "kakunaka",
        "JP"
    ),
    (
        "Magnetman210#3917",
        "adryan-sutantoso-2",
        "MagnetmanVGC",
        NULL,
        "Magnetman",
        "ID"
    ),
    (
        "Maquia#7386",
        "teamathenawifibattles",
        "heliosofsunvgc",
        NULL,
        "Helios",
        "SG"
    ),
    (
        "Meta Knight 1320#6620",
        "metaknight1320",
        NULL,
        NULL,
        "Metaknight",
        "CL"
    ),
    (
        "Mr.PokÉnjoy#8551",
        "unknown5bc1393935b6fd03bd1d63fb",
        "Mr_PokEnjoy",
        NULL,
        "Pokenjoy",
        "JP"
    ),
    (
        "nanoooooo#4580",
        "purplemecf",
        NULL,
        NULL,
        "Nanoooooo",
        "ID"
    ),
    (
        "Nintendolphin#2016",
        "826672284",
        "Nintendolphins",
        NULL,
        "花寄寮VGC/Nintendolphins",
        "CN"
    ),
    (
        "pikuchanneru#0277",
        "pikuchanneru",
        "pikuchanneru",
        NULL,
        "Piku",
        "ID"
    ),
    (
        "Raya Stark#5370",
        "raymond_squared",
        NULL,
        NULL,
        "Raya Stark",
        "ID"
    ),
    ("Rey J#2898", "reynism", NULL, NULL, "reynism", "ID"),
    (
        "Roversombra#2603",
        "earaaguaron",
        "roversombra",
        NULL,
        "Roversombra",
        "ES"
    ),
    (
        "scar1et#7427",
        "_scar1et_",
        "scarlet_ik",
        NULL,
        "すかーれっと",
        "CN"
    ),
    (
        "Shadowmime#4734",
        "shadowmime",
        NULL,
        NULL,
        "Shadowmime",
        "AU"
    ),
    (
        "SoulKnight66#1317",
        "zacharychia12",
        "SoulKnight66",
        NULL,
        "SoulKnightVGC",
        "SG"
    ),
    (
        "Sportaholic#6548",
        "Sportaholic_21",
        "Sportaholic_21",
        NULL,
        "Long",
        "VN"
    ),
    (
        "TehDrink#2458",
        "tehdrink",
        "tehdrink",
        NULL,
        "tehdrink/Kester",
        "SG"
    ),
    (
        "Tide(消波塊)#4240",
        "ga0620ry",
        "ga0620ryTW",
        NULL,
        "YaYeee",
        "TW"
    ),
    (
        "Tomoe#0100",
        "rivenbeatsfiora",
        NULL,
        NULL,
        "Tomoe",
        "PH"
    ),
    (
        "updateVGC#0036",
        "updatevgc",
        "updateVGC",
        NULL,
        "updatevgc",
        "BD"
    ),
    (
        "YuyuVGC#3501",
        "1457201939",
        NULL,
        NULL,
        "YuyuVGC/彧",
        "CN"
    ),
    (
        "がはく#2290",
        "pochapencil",
        "gahaku_poke",
        NULL,
        "gahaku",
        "JP"
    ),
    (
        "ゴートゥ#4685",
        "ゴートゥ",
        "GotoTapuFiniVGC",
        NULL,
        "ゴートゥ",
        "JP"
    ),
    (
        "ぺい#9801",
        "pokepei17",
        "pokepei17",
        NULL,
        "Paypay",
        "JP"
    ),
    ("在水之番#9726", "465943395", NULL, NULL, "在水之番", "CN"),
    ("小羚羊#0314", "happy-lv", NULL, NULL, "吕", "CN"),
    ("洛觞#1925", "2517534808", NULL, NULL, "洛觞", "CN") ON CONFLICT (id) DO
UPDATE
SET
    discord = EXCLUDED.discord,
    battlefy = EXCLUDED.battlefy,
    twitter = EXCLUDED.twitter,
    realname = EXCLUDED.realname,
    nickname = EXCLUDED.nickname,
    country = EXCLUDED.country,
    created_by = EXCLUDED.created_by,
    updated_by = EXCLUDED.updated_by;